#!/bin/bash

## local variables
SERVER_VERSION="$1"
RANCHER_CONTAINER='rancher'
OPERATING_SYSTEM=$(uname -s)

## detect os
case "${OPERATING_SYSTEM}" in
    Linux*)
        DISTRO_TYPE='linux';;
    Darwin*)
        DISTRO_TYPE='unix';;
    CYGWIN*)
        DISTRO_TYPE='windows';;
    MINGW*)
        DISTRO_TYPE='windows';;
    *)
        echo ''
        echo 'Error: operating system not known, please open an issue:'
        echo ''
        echo 'https://github.com/jeff1evesque/machine-learning/issues/new'
        echo ''
        exit 1
esac

## install rancher server
sudo docker run -d \
    --name "$RANCHER_CONTAINER" \
    --restart=unless-stopped \
    -p 8080:8080 \
    rancher/server:"$SERVER_VERSION"
