#!/bin/bash

## local variables
SERVER_VERSION="$1"
RANCHER_CONTAINER='rancher'

## detect os
case "${OPERATING_SYSTEM}" in
    Linux*)
        DISTRO_TYPE='linux'
    Darwin*)
        DISTRO_TYPE='unix'
    CYGWIN*)
        DISTRO_TYPE='windows'
    MINGW*)
        DISTRO_TYPE='windows'
    *)
        echo ''
        echo 'Error: operating system not known, please open an issue:'
        echo ''
        echo 'https://github.com/jeff1evesque/machine-learning/issues/new'
        echo ''
        exit 1
esac

## install rancher server
docker run -d \
    --name "$RANCHER_CONTAINER" \
    --restart=unless-stopped \
    -p 8080:8080 \
    rancher/server:"$SERVER_VERSION"

## legacy windows uses docker toolbox, which requires 'default' container
if [ "$DISTRO_TYPE" = 'windows' ] && [ "$WINDOWS_CURRENT_VERSION" -le "$WINDOWS_VERSION" ]; then
    echo ''
    echo 'Windows docker implementation, requires DockerToolbox, which'
    echo "creates a 'default' container to manage docker. To proceed,"
    echo "rancher configurations will reflect port '8080'."
    echo ''

    RANCHER_CONTAINER='default'
    SERVER_IP=$(docker-machine ip 'default')

else
    SERVER_IP=$(docker inspect -f "{{ .NetworkSettings.IPAddress }}" "$RANCHER_CONTAINER")
fi

## store ip
echo "$SERVER_IP" > rancher_ip.txt
